# Generated by Django 4.1.5 on 2023-08-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ElevationOrFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.building')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('elevation_or_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.elevationorfloor')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityTakeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_code', models.CharField(max_length=200)),
                ('manufacturing_code', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('width', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('multiplier2', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('take_out', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.building')),
                ('elevation_or_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.elevationorfloor')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.place')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.project')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.section')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.section'),
        ),
    ]
