# Generated by Django 4.1.5 on 2023-05-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_code', models.IntegerField()),
                ('provider_company', models.CharField(max_length=255)),
                ('reciever_company', models.CharField(max_length=255)),
                ('inflow_outflow', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('place_of_use', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('subgroup', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField(unique=True)),
                ('barcode', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('subgroup', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField(unique=True)),
                ('barcode', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('subgroup', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('warehouse', models.CharField(max_length=255)),
                ('inflow', models.FloatField(null=True)),
                ('outflow', models.FloatField(null=True)),
                ('stock', models.FloatField(null=True)),
            ],
        ),
    ]
