# Generated by Django 3.2.5 on 2023-08-02 10:47

from django.db import migrations, models
import django.db.models.deletion
import koz_stock_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0002_alter_productinflow_receiver_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=koz_stock_api.models.RandomFileName('product_images/'))),
                ('product_inflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='koz_stock_api.productinflow')),
            ],
        ),
    ]
