# Generated by Django 4.1.5 on 2023-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0002_productflow_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productflow',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
