# Generated by Django 3.2.5 on 2023-09-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0003_alter_quantitytakeoff_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitytakeoff',
            name='pose_number',
            field=models.IntegerField(null=True),
        ),
    ]
