# Generated by Django 4.1.5 on 2023-05-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0003_productflow_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productflow',
            name='barcode',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
