# Generated by Django 4.1.5 on 2023-08-05 11:40

from django.db import migrations, models
import django.db.models.deletion
import koz_stock_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0003_productimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductInflowImage',
        ),
        migrations.CreateModel(
            name='ProductOutflowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=koz_stock_api.models.RandomFileName('product_images/'))),
                ('product_outflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='koz_stock_api.productoutflow')),
            ],
        ),
    ]
