# Generated by Django 4.1.5 on 2023-05-17 11:13

import dirtyfields.dirtyfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0004_productflow_barcode_alter_stock_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_code', models.IntegerField()),
                ('barcode', models.CharField(max_length=255)),
                ('provider_company', models.CharField(max_length=255)),
                ('reciever_company', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('place_of_use', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('subgroup', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('amount', models.FloatField(null=True)),
                ('unit_price', models.FloatField(null=True)),
                ('discount_rate', models.FloatField(null=True)),
                ('discount_amount', models.FloatField(null=True)),
                ('tax_rate', models.FloatField(null=True)),
                ('tevkifat_rate', models.FloatField(null=True)),
                ('price_without_tax', models.FloatField(null=True)),
                ('price_with_tevkifat', models.FloatField(null=True)),
                ('price_total', models.FloatField(null=True)),
            ],
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
    ]
