# Generated by Django 4.1.5 on 2023-05-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0005_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_accountingstaff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_stockstaff',
            field=models.BooleanField(default=False),
        ),
    ]
