# Generated by Django 4.1.5 on 2023-10-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0005_alter_stock_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinflow',
            old_name='barcode',
            new_name='bill_number',
        ),
        migrations.RemoveField(
            model_name='productinflow',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='productinflow',
            name='place_of_use',
        ),
        migrations.RemoveField(
            model_name='productinflow',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinflow',
            name='status',
        ),
        migrations.CreateModel(
            name='ProductInflowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=255)),
                ('place_of_use', models.CharField(max_length=255)),
                ('amount', models.FloatField(null=True)),
                ('inflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='koz_stock_api.productinflow')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='koz_stock_api.products')),
            ],
        ),
    ]
