# Generated by Django 4.1.5 on 2023-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0006_rename_barcode_productinflow_bill_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='adress',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='consumers',
            name='explanation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='consumers',
            name='mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='adress',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='explanation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consumers',
            name='contact_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consumers',
            name='contact_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='contact_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='contact_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
