# Generated by Django 4.1.5 on 2023-05-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0007_company_project_customuser_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productflow',
            old_name='barcode',
            new_name='receiver_company',
        ),
        migrations.RemoveField(
            model_name='productflow',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productflow',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productflow',
            name='group',
        ),
        migrations.RemoveField(
            model_name='productflow',
            name='model',
        ),
        migrations.RemoveField(
            model_name='productflow',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='productflow',
            name='reciever_company',
        ),
        migrations.RemoveField(
            model_name='productflow',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='productflow',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='productflow',
            name='unit',
        ),
        migrations.AddField(
            model_name='accounting',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounting',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productflow',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productflow',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productflow',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.project'),
            preserve_default=False,
        ),
    ]
