# Generated by Django 4.1.5 on 2023-10-04 10:34

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0007_consumers_adress_consumers_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_without_tax', models.FloatField()),
                ('unit_price_without_tax', models.FloatField()),
                ('price_with_tevkifat', models.FloatField()),
                ('price_total', models.FloatField()),
                ('product_inflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.productinflow')),
            ],
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='AccountingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('discount_rate', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('tax_rate', models.FloatField()),
                ('tevkifat_rate', models.FloatField(default=0)),
                ('price_without_tax', models.FloatField()),
                ('unit_price_without_tax', models.FloatField()),
                ('price_with_tevkifat', models.FloatField()),
                ('price_total', models.FloatField()),
                ('accounting_inflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='koz_stock_api.accountinginflow')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.productinflowitem')),
            ],
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
    ]
