# Generated by Django 4.1.5 on 2023-05-26 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0008_rename_barcode_productflow_receiver_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='group',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='model',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit',
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.products'),
            preserve_default=False,
        ),
    ]
