# Generated by Django 4.1.5 on 2023-10-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0008_accountinginflow_accountingitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounting',
        ),
    ]
