# Generated by Django 4.1.5 on 2023-05-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0009_remove_stock_barcode_remove_stock_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='barcode',
            new_name='receiver_company',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='group',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='model',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='reciever_company',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='unit',
        ),
        migrations.AddField(
            model_name='accounting',
            name='product',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.PROTECT, to='koz_stock_api.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='koz_stock_api.products'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='koz_stock_api.products'),
        ),
    ]
