# Generated by Django 4.1.5 on 2023-05-30 12:21

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0010_rename_barcode_accounting_receiver_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=350)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.company')),
            ],
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='ProductInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('barcode', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=255)),
                ('place_of_use', models.CharField(max_length=255)),
                ('amount', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.company')),
            ],
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='ProductOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('barcode', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=255)),
                ('place_of_use', models.CharField(max_length=255)),
                ('amount', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.company')),
            ],
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=350)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.company')),
            ],
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.RenameField(
            model_name='accounting',
            old_name='amount',
            new_name='unit_price_without_tax',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='place_of_use',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='product',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='provider_company',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='receiver_company',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='status',
        ),
        migrations.RemoveField(
            model_name='products',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='products',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='products',
            name='supplier_contact',
        ),
        migrations.AddField(
            model_name='stock',
            name='reserve_stock',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='ProductFlow',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='products',
            field=models.ManyToManyField(to='koz_stock_api.products'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.project'),
        ),
        migrations.AddField(
            model_name='productoutflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='koz_stock_api.products'),
        ),
        migrations.AddField(
            model_name='productoutflow',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.project'),
        ),
        migrations.AddField(
            model_name='productoutflow',
            name='receiver_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_outflows', to='koz_stock_api.consumers'),
        ),
        migrations.AddField(
            model_name='productoutflow',
            name='supplier_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_outflows', to='koz_stock_api.consumers'),
        ),
        migrations.AddField(
            model_name='productinflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='koz_stock_api.products'),
        ),
        migrations.AddField(
            model_name='productinflow',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.project'),
        ),
        migrations.AddField(
            model_name='productinflow',
            name='receiver_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_inflows', to='koz_stock_api.suppliers'),
        ),
        migrations.AddField(
            model_name='productinflow',
            name='supplier_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_inflows', to='koz_stock_api.suppliers'),
        ),
        migrations.AddField(
            model_name='consumers',
            name='products',
            field=models.ManyToManyField(to='koz_stock_api.products'),
        ),
        migrations.AddField(
            model_name='consumers',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.project'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='product_inflow',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='koz_stock_api.productinflow'),
            preserve_default=False,
        ),
    ]
