# Generated by Django 4.1.5 on 2023-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0012_alter_customuser_is_active_productgroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroups',
            name='group_code',
            field=models.IntegerField(null=True),
        ),
    ]
