# Generated by Django 4.1.5 on 2023-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0013_alter_productgroups_group_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='consumers',
            name='tax_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='tax_code',
            field=models.IntegerField(),
        ),
    ]
