# Generated by Django 4.1.5 on 2023-06-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0014_sequencenumber_alter_consumers_tax_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(max_length=255),
        ),
    ]
