# Generated by Django 3.2.5 on 2023-06-22 08:34

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koz_stock_api', '0015_alter_products_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumers',
            name='project',
        ),
        migrations.RemoveField(
            model_name='productgroups',
            name='project',
        ),
        migrations.RemoveField(
            model_name='products',
            name='project',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='project',
        ),
        migrations.AddField(
            model_name='consumers',
            name='projects',
            field=models.ManyToManyField(related_name='consumers', to='koz_stock_api.Project'),
        ),
        migrations.AddField(
            model_name='productgroups',
            name='projects',
            field=models.ManyToManyField(related_name='product_groups', to='koz_stock_api.Project'),
        ),
        migrations.AddField(
            model_name='products',
            name='projects',
            field=models.ManyToManyField(related_name='products', to='koz_stock_api.Project'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='projects',
            field=models.ManyToManyField(related_name='suppliers', to='koz_stock_api.Project'),
        ),
        migrations.AlterField(
            model_name='products',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='koz_stock_api.productgroups'),
        ),
        migrations.CreateModel(
            name='ProductSubgroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup_code', models.IntegerField(null=True)),
                ('subgroup_name', models.CharField(max_length=255)),
                ('sequence_number', models.IntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='koz_stock_api.productgroups')),
            ],
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.AlterField(
            model_name='products',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='koz_stock_api.productsubgroups'),
        ),
    ]
